name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
autolabeler:
  - label: 'chore'
    title:
      - '/chore:/i'
      - '/docs:/i'
      - '/ci:/i'
    branch:
      - '/fix-/'
  - label: 'bug'
    title:
      - '/fix:/i'
    branch:
      - '/fix-/'
  - label: 'feature'
    title:
      - '/feat:/i'
    branch:
      - '/feat-/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES